---
# tasks file for server
 - name: Install mysql-server
   become: true
   apt:
     pkg: mysql-server
     update_cache: yes
     cache_valid_time: 86400
     state: present
   when: ansible_distribution == 'Ubuntu'

# - name: Install apache
#   become: true
#   apt:
#     pkg: apache2
#     update_cache: yes
#     cache_valid_time: 86400
#     state: latest
#   when: ansible_distribution == 'Ubuntu'

# - name: install required software
#   become: true
#   apt: name={{ item }} state=present 
#   with_items: 
#     - apache2
#     - mysql-server
#     - php7.2-mysql
#     - php7.2
#     - libapache2-mod-php7.2
#     - python-mysqldb
# - name: install required software
#   become: true
#   apt: name="{{ item }}" state=latest
#   with_items: 
#     - apache2
#     - mysql-server
#     - php7.2-mysql
#     - php7.2
#     - libapache2-mod-php7.2
#     - python-mysqldb